name: proyek_submission_mpd
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

dependencies:
  analyzer: ^9.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
